sudo: required
services:
  - docker

before_install:
  - docker build -t ian035/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ian035/react-test npm run test

after_success:
  - docker build -t ian035/multi-client ./client
  - docker build -t ian035/multi-nginx ./nginx
  - docker build -t ian035/multi-server ./server
  - docker build -t ian035/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ian035/multi-client
  - docker push ian035/multi-nginx
  - docker push ian035/multi-server
  - docker push ian035/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'docker-demo'
  env: 'DockerDemo-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-406965596077'
  bucket_path: 'docker-demo'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
